# Generated by Django 4.0.6 on 2022-09-26 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='Shipment Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='Shipment Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField(verbose_name='Product quantity at Selling Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_order_product', to='products.product', verbose_name='Product')),
                ('selling_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_order_product', to='orders.sellingorder', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sellingorder',
            name='products',
            field=models.ManyToManyField(related_name='selling_orders', through='orders.SellingOrderProduct', to='products.product', verbose_name='Products'),
        ),
        migrations.CreateModel(
            name='BuyingOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField(verbose_name='Product quantity at Buying Order')),
                ('buying_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_order_product', to='orders.buyingorder', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_order_product', to='products.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='buyingorder',
            name='products',
            field=models.ManyToManyField(related_name='buying_orders', through='orders.BuyingOrderProduct', to='products.product', verbose_name='Products'),
        ),
    ]
