# Generated by Django 4.0.5 on 2022-06-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=8)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
