# Generated by Django 4.0.5 on 2022-06-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
