# Generated by Django 4.0.6 on 2022-07-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField(verbose_name='Product quantity at Inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(related_name='inventories', through='backend_api.InventoryProduct', to='backend_api.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='backend_api.supplier', verbose_name='Inventory'),
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='backend_api.inventory', verbose_name='Inventory'),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='backend_api.product', verbose_name='Product'),
        ),
    ]
