# Generated by Django 4.0.6 on 2022-07-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shipment Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='backend_api.OrderProduct', to='backend_api.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend_api.supplier', verbose_name='Supplier'),
        ),
    ]
