# Generated by Django 4.0.5 on 2022-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_product_cost_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ref', models.CharField(max_length=9, verbose_name='Reference')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
