# Generated by Django 4.0.6 on 2022-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_inventoryproduct_alter_inventory_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Product quantity at Order'),
        ),
    ]
