# Generated by Django 4.0.6 on 2022-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(to='backend_api.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ref',
            field=models.CharField(max_length=6, verbose_name='Reference'),
        ),
    ]
