# Generated by Django 4.0.6 on 2022-07-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='backend_api.supplier', verbose_name='Inventory'),
        ),
    ]
