# Generated by Django 4.0.6 on 2022-07-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_stock_products_alter_stock_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ref', models.CharField(default='', max_length=6, verbose_name='Reference')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='address',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ref',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(default='', to='backend_api.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_place',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_api.stockplace', verbose_name=''),
            preserve_default=False,
        ),
    ]
