# Generated by Django 4.0.6 on 2022-07-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_stockplace_remove_stock_address_remove_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(related_name='products', to='backend_api.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='backend_api.stockplace', verbose_name='Stock Place'),
        ),
        migrations.AlterField(
            model_name='stockplace',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
    ]
