# Generated by Django 4.0.6 on 2022-07-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='products',
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='backend_api.product', verbose_name='Products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_place', to='backend_api.stockplace', verbose_name='Stock Place'),
        ),
    ]
